### ISSUE TITLE
As a User, I want a breadcrumb navigation bar in member and union pages

### ISSUE THREAD

**Issue by d9beuD** [d9beuD/genealogist#57]

**Comment by Shankar009378** [comment]
Hii! 
I have understand your problem please assign me this work I can fix that

**Comment by d9beuD** [comment]
Hi @Shankar009378! I would love to receive some help as it would be time saving for me. I appreciate that, thanks.

Can you use Bootstrap's [Breadcrumb](https://getbootstrap.com/docs/5.3/components/breadcrumb/) component for this feature, please?

Examples of what I was expecting:

Page `/tree/{treeId}/person/{personId}`, the breadcrumb should show something like:
> [Tree name]

Page `/person/{personId}/union/{unionId}`, the breadcrumb should show something like:
> [Tree name] / [Person full name]

Is that okay for you?

**Comment by Shankar009378** [comment]
Yes it will be okay for me

**Comment by d9beuD** [comment]
Just to let you know that I updated README.md file with usage instructions.

**Comment by Shankar009378** [comment]
Done.Please accept the pull request and see
